location                = "westeurope"
base_name               = "OperaTerra"
sa_ak_secret_name       = "saaksecret"
vm_username_secret_name = "adminUserName"
vm_username             = "adminUser"
vm_passwd_secret_name   = "adminPassword"
vm_passwd               = "S@mpleP@sswØrd123"
